image:
  repository: diluniamarasekara/colombo-stock-exchange
  tag: latest-version

env:
  - name: "DATABASE_HOSTNAME"
    value: "db-postgresql-sgp1-colombo-stock-exchange-do-user-13208630-0.b.db.ondigitalocean.com"
  - name: "DATABASE_PORT"
    value: "25060"
  - name: "DATABASE_USER"
    value: "root"

secrets:
  - name: DATABASE_PASSWORD
    value: ${{ secrets.DATABASE_PASSWORD }}

service:
  type: LoadBalancer
  internalPort: 8090    

# livenessProbe -- Customize the livenessProbe.
livenessProbe:
  httpGet:
    path: /actuator/health
    port: http

# readinessProbe -- Customize the readiness probe.
readinessProbe:
  httpGet:
    path: /actuator/health
    port: http