name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: 'Deploy'
        uses: 'vimeda/helm@v1.6.8'
        with:
          release: 'stock-exchange'
          namespace: 'stock-exchange'
          chart: 'helm'
          token: '${{ github.token }}'
          value-files: >-
            [
              "config/values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'